### ISSUE TITLE
Meta::TeamTracking tag update

### ISSUE THREAD

**Issue by jaliasd** [USAID-OHA-SI/TeamTracking#45]
We need to review and update the tags we have for COP support specifically, but also anticipating a division -wide roll out of a ticketing system.

- [ ] Review current tags for relevance, delete as needed

- [ ] New tags within the existing categories

- [ ]  New/re-do categorization

- [ ] Re-do tag listing in readme in markup
